CREATE DATABASE parking;
CREATE TABLE ADMIN_ACCOUNT(
	id CHAR(6) NOT NULL PRIMARY KEY,
	pw CHAR(6) NOT NULL
);

INSERT INTO ADMIN_ACCOUNT VALUES('A11111', 'A11111');
INSERT INTO ADMIN_ACCOUNT VALUES('B11111', 'B11111');
INSERT INTO ADMIN_ACCOUNT VALUES('C11111', 'C11111');
INSERT INTO ADMIN_ACCOUNT VALUES('D11111', 'D11111');

CREATE TABLE HISTORY(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	admin_id CHAR(6) NOT NULL,
	park_area TINYINT NOT NULL,
	park_spot TINYINT NOT NULL,
	car_no VARCHAR(11) NOT NULL,
	enter_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	exit_time TIMESTAMP,
 	
	CONSTRAINT admin_id_FK FOREIGN KEY (admin_id) REFERENCES ADMIN_ACCOUNT(id)
);

INSERT INTO HISTORY(admin_id, park_area, park_spot, car_no) VALUES('A11111', 1, 1, '111가1111');

CREATE TABLE PARK_IMAGE(
	history_id INT NOT NULL UNIQUE,
	image_name VARCHAR(75) NOT NULL,
	
	CONSTRAINT history_id_FK FOREIGN KEY (history_id) REFERENCES HISTORY(id)
);



SELECT * FROM HISTORY WHERE exit_time IS NULL;
// 사진 16메가
create user 'parkadmin'@localhost identified by 'mysql';
GRANT ALL PRIVILEGES ON parking.* TO parkadmin@localhost;