spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: parkadmin
    password: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB