CREATE DATABASE parking;
CREATE TABLE ADMIN_ACCOUNT(
	id CHAR(6) NOT NULL PRIMARY KEY,
	pw CHAR(6) NOT NULL
);

INSERT INTO ADMIN_ACCOUNT VALUES('A11111', 'A11111');
INSERT INTO ADMIN_ACCOUNT VALUES('B11111', 'B11111');
INSERT INTO ADMIN_ACCOUNT VALUES('C11111', 'C11111');
INSERT INTO ADMIN_ACCOUNT VALUES('D11111', 'D11111');

CREATE TABLE CAR_REGION(
	region_no TINYINT NOT NULL PRIMARY KEY,
	region_name CHAR(2) NOT NULL UNIQUE
);

INSERT INTO CAR_REGION VALUES(0, '--');
INSERT INTO CAR_REGION VALUES(1, '서울');
INSERT INTO CAR_REGION VALUES(2, '경기');
INSERT INTO CAR_REGION VALUES(3, '인천');
INSERT INTO CAR_REGION VALUES(4, '부산');
INSERT INTO CAR_REGION VALUES(5, '대구');
INSERT INTO CAR_REGION VALUES(6, '광주');
INSERT INTO CAR_REGION VALUES(7, '대전');
INSERT INTO CAR_REGION VALUES(8, '강원');
INSERT INTO CAR_REGION VALUES(9, '충북');
INSERT INTO CAR_REGION VALUES(10, '충남');
INSERT INTO CAR_REGION VALUES(11, '전북');
INSERT INTO CAR_REGION VALUES(12, '전남');
INSERT INTO CAR_REGION VALUES(13, '경북');
INSERT INTO CAR_REGION VALUES(14, '경남');
INSERT INTO CAR_REGION VALUES(15, '제주');

CREATE TABLE HISTORY(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	admin_id CHAR(6) NOT NULL,
	park_area TINYINT NOT NULL,
	park_spot TINYINT NOT NULL,
	car_region_no TINYINT NOT NULL,
	car_no VARCHAR(9) NOT NULL,
	enter_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	exit_time TIMESTAMP,
 	
	CONSTRAINT admin_id_FK FOREIGN KEY (admin_id) REFERENCES ADMIN_ACCOUNT(id),
	CONSTRAINT car_region_no_FK FOREIGN KEY (car_region_no) REFERENCES CAR_REGION(region_no)
);

INSERT INTO HISTORY(admin_id, park_area, park_spot, car_region_no, car_no) VALUES('A11111', 1, 1, 0, '111가1111');

CREATE TABLE PARK_IMAGE(
	history_id INT NOT NULL UNIQUE,
	image_name CHAR(42) NOT NULL,
	
	CONSTRAINT history_id_FK FOREIGN KEY (history_id) REFERENCES HISTORY(id)
);

INSERT INTO PARK_IMAGE VALUES(2, LOAD_FILE('C:\\ProgramData\\MySQL\\MySQL Server 8.3\\Uploads\\suga_zinza.jpg'));
SELECT * FROM HISTORY WHERE exit_time IS NULL;
// 사진 16메가
create user 'parkadmin'@localhost identified by 'mysql';
GRANT ALL PRIVILEGES ON parking.* TO parkadmin@localhost;